name: schedule_kpi
description: Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_keyboard_visibility: ^5.0.0
  http: ^0.13.0
  image_picker: ^0.7.3
  intl: ^0.17.0-nullsafety.2
  path: ^1.8.0-nullsafety.3
  percent_indicator: ^3.3.0-nullsafety.1
  provider: ^5.0.0-nullsafety.2
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/

  fonts:
    - family: DniproCity
      fonts:
        - asset: assets/fonts/DniproCity-Bold.ttf
flutter_intl:
  enabled: true
